src/Entity/Field/AdminFieldFormInterface.php
<?php


namespace Farvest\AdminBundle\Entity\Field;


use Farvest\AdminBundle\Utils\KeyValueCollection;

interface AdminFieldFormInterface
{
    public function getTypeClass(): string;
    public function getOptions(): KeyValueCollection;

    public function addOption($option, $key): self;
    public function removeOption($option): self;
}

src/Resources/views/pages/list.html.twig
{% extends '@FarvestAdmin/base.html.twig' %}

{# @var AdminListTemplate entityList #}

{% block body %}
    {% if builderErrors %}
        {% for error in builderErrors %}
            {{ error }}<br />
        {% endfor %}
    {% endif %}
    <h3 class="title">{{ entityList.title }}</h3>
    <table>
        <thead>
        <tr>
            {% for entityFieldTitle in entityList.fields %}
                {% set field = entityFields.get(entityFieldTitle) %}
                <th {% if field.fieldList.style != null %}style="{{ field.fieldList.style }}"{% endif %}>
                    {{ field.fieldLabel }}
                </th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for dataList in data %}
            <tr>
                {% for entityFieldTitle in entityList.fields %}
                    {% set field = entityFields.get(entityFieldTitle) %}
                    {% set type = field.fieldForm.typeClass %}
                    <td {% if field.fieldList.style != null %}style="{{ field.fieldList.style }}"{% endif %}>
                        {% if typeClass == "Symfony\\Component\\Form\\Extension\\Core\\Type\\TextType" %}
                            {{ attribute(dataList, entityFieldTitle) }}
                        {% elseif typeClass == "Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType" %}
                            {% set joinData = dataList(entityFields.get(entityFieldTitle).fieldForm.entity) %}
                            {% if joinData is not null %}
                                {{ attribute(joinData, entityFields.get(entityFieldTitle).fieldList.listDisplay) }}
                            {% endif %}
                        {% endif %}
                    </td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}